name: celluloid
base: core22
adopt-info: celluloid
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

slots:
  celluloid:
    interface: dbus
    bus: session
    name: io.github.celluloid_player.Celluloid
  mpris:
    name: Celluloid

apps:
  celluloid:
    command: usr/bin/celluloid
    extensions: [gnome]
    environment:
      PYTHONPATH: ${SNAP}/lib/python3.10/site-packages:${SNAP}/usr/lib/python3/dist-packages
    common-id: io.github.celluloid_player.Celluloid
    desktop: usr/share/applications/io.github.celluloid_player.Celluloid.desktop
    plugs:
      - home
      - audio-playback
      - bluez
      - network
      - network-bind
      - network-status
      - removable-media
      - unity7
      - optical-drive
      - screen-inhibit-control
    slots:
      - mpris

parts:
  ffmpeg:
    plugin: autotools
    source: https://ffmpeg.org/releases/ffmpeg-6.0.tar.xz
    source-checksum: sha256/57be87c22d9b49c112b6d24bc67d42508660e6b718b3db89c44e47e289137082
    autotools-configure-parameters:
      - --prefix=/usr
      - --libdir=/usr/lib/$CRAFT_ARCH_TRIPLET
      - --disable-debug
      - --disable-doc
      - --disable-static
      - --enable-gpl
      - --enable-shared
      - --disable-ffplay
      - --disable-devices
      - --enable-gnutls
      - --enable-libmp3lame
      - --enable-libvorbis
    build-packages:
      - nasm
      - libmp3lame-dev
      - libvorbis-dev
    stage-packages:
      - libmp3lame0
    prime:
      - -usr/share/doc
      - -usr/share/man
      - -usr/share/ffmpeg/examples
      - -usr/include
      - -usr/lib/*/pkgconfig

  mpv:
    source: https://github.com/mpv-player/mpv.git
    source-tag: v0.36.0
    after: [ffmpeg]
    plugin: meson
    meson-parameters:
      - -Dprefix=/usr
      - -Dbuildtype=release
      - -Dlibmpv=true
      - -Dx11=enabled
      - -Dwayland=enabled
    build-packages:
      - curl
      - libx264-dev
      - libass-dev
      - libvorbis-dev
      - libjpeg-turbo8-dev
      - libxss-dev
      - libxpresent-dev
    prime:
      - -usr/share
      - -usr/include
      - -usr/lib/*/pkgconfig

  yt-dlp:
    plugin: python
    after: [mpv]
    source: https://github.com/yt-dlp/yt-dlp/releases/download/2023.07.06/yt-dlp.tar.gz
    source-checksum: sha256/6d2115b84b6c11867f92cf4c23705b536bfa0ba9d538b1885f52da6756f8c980
    python-packages:
      - pyxattr==0.8.1
    build-environment:
      - PATH: ${CRAFT_PART_INSTALL}/bin:${PATH}
      - PYTHONPATH: ""
    override-pull: |
      craftctl default
      sed -i 's/^certifi\b/#\0/' requirements.txt
    stage:
      - -bin/activate*
      - -bin/Activate.ps1
      - -bin/python*
      - -bin/pip*
      - -pyvenv.cfg
      - -lib/**/setuptools*
      - -lib/**/pip*
      - -share/doc
      - -share/man

  celluloid:
    source: https://github.com/celluloid-player/celluloid.git
    source-tag: v0.26
    after: [yt-dlp]
    plugin: meson
    parse-info: [usr/share/metainfo/io.github.celluloid_player.Celluloid.appdata.xml]
    meson-parameters:
      - -Dprefix=/usr
    build-packages:
      - libass-dev
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0 | cut -c 2-)
    prime:
      - -usr/share/man
      - -usr/include
      - -usr/lib/*/pkgconfig

  deps:
    plugin: nil
    after: [celluloid]
    stage-packages:
      - libxpresent1
      - libxss1
      - libass9
    prime:
      - usr/lib/*/libass*
      - usr/lib/*/libXss*
      - usr/lib/*/libXpresent*

  cleanup:
    after:
      - deps
    plugin: nil
    build-snaps:
      - gnome-42-2204
      - core22
      - gtk-common-themes
    override-prime: |
      set -eux
      for snap in "gnome-42-2204" "core22" "gtk-common-themes"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$CRAFT_PRIME/{}" \;
      done
