name: celluloid
base: core22
adopt-info: celluloid  
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
  
slots:
  celluloid:
    interface: dbus
    bus: session
    name: io.github.celluloid_player.Celluloid
  mpris:
    name: Celluloid
    
environment:
  # WORKAROUND: Add python modules in Snap to search path (Need changes)
  PYTHONPATH: ${SNAP}/lib/python3.10/site-packages:${SNAP}/usr/lib/python3/dist-packages

apps:
  celluloid:
    command: usr/bin/celluloid
    extensions: [gnome]
    common-id: io.github.celluloid_player.Celluloid 
    desktop: usr/share/applications/io.github.celluloid_player.Celluloid.desktop
    plugs:
      - home
      - audio-playback
      - bluez
      - network
      - network-bind
      - network-status
      - removable-media
      - unity7
      - optical-drive
      - screen-inhibit-control
    slots:
      - mpris
    
parts: 
  ffmpeg:
    plugin: autotools
    source: https://ffmpeg.org/releases/ffmpeg-6.0.tar.xz
    source-checksum: sha256/57be87c22d9b49c112b6d24bc67d42508660e6b718b3db89c44e47e289137082
    after: [libass]
    autotools-configure-parameters:
      - --prefix=/usr
      - --libdir=/usr/lib/$CRAFT_ARCH_TRIPLET
      - --disable-debug
      - --disable-doc
      - --disable-static
      - --enable-gpl
      - --enable-shared
      - --disable-ffplay
      - --disable-devices
      - --enable-gnutls
      - --enable-libmp3lame
      - --enable-libvorbis
    build-packages:
      - nasm
      - libgnutls28-dev
      - libmp3lame-dev
      - libvorbis-dev
    stage-packages:
      - libmp3lame0
    
  mpv:
    source: https://github.com/mpv-player/mpv.git
    source-tag: v0.35.1
    after: [ffmpeg]
    plugin: meson
    meson-parameters:
      - -Dprefix=/usr
      - -Dbuildtype=release
      - -Dlibmpv=true
      - -Dx11=enabled
      - -Dwayland=enabled
    build-packages:
      - curl
      - libx264-dev
      - libvorbis-dev
      - libjpeg-turbo8-dev
      #- libpipewire-0.3-dev
    prime:
      - usr/lib/*/libmpv*
      
  xss:
    source: https://gitlab.freedesktop.org/xorg/lib/libxscrnsaver.git
    source-tag: libXScrnSaver-1.2.4
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr   
    build-packages: 
      - x11proto-dev
      - xutils-dev
      - libxext-dev    
    
  xpresent:
    source: https://gitlab.freedesktop.org/xorg/lib/libxpresent.git
    source-tag: libXpresent-1.0.1
    after: [xss]
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr 
    build-packages: 
      - x11proto-dev
      - xutils-dev
      - libxext-dev    
        
  libass:
    source: https://github.com/libass/libass/releases/download/0.17.1/libass-0.17.1.tar.xz
    after: [xpresent]
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr 
      - --disable-static 
      - --disable-fontconfig
      - --disable-require-system-font-provider
  
  celluloid:
    source: https://github.com/celluloid-player/celluloid.git
    source-tag: v0.25
    after: [yt-dlp]
    plugin: meson
    parse-info: [usr/share/metainfo/io.github.celluloid_player.Celluloid.appdata.xml]
    meson-parameters:
      - -Dprefix=/usr
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0 | cut -c 2-)
    
  yt-dlp:
    # Missing optional dependencies atomicparsley,phantomjs and rtmpdump
    plugin: python
    after: [mpv]
    source: https://github.com/yt-dlp/yt-dlp/releases/download/2023.07.06/yt-dlp.tar.gz
    source-checksum: sha256/6d2115b84b6c11867f92cf4c23705b536bfa0ba9d538b1885f52da6756f8c980
    python-packages:
      - pyxattr==0.7.2
    build-environment:
      # WORKAROUND: The python plugin is broken with gnome extension
      - PATH: ${CRAFT_PART_INSTALL}/bin:${PATH}
      - PYTHONPATH: ""
    override-pull: |
      craftctl default
      sed -i 's/^certifi\b/#\0/' requirements.txt
    stage:
      # WORKAROUND: Skip venv from python plugin
      - -bin/activate
      - -bin/activate.csh
      - -bin/activate.fish
      - -bin/Activate.ps1
      - -bin/python
      - -bin/python3
      - -bin/python3.10
      - -bin/pip
      - -bin/pip3
      - -bin/pip3.10
      - -pyvenv.cfg
 
  fatloss:
    after: [celluloid]
    plugin: nil
    override-prime:
      craftctl default |
      rm -r usr/include
      rm -r usr/share/doc
      
  cleanup:
    after:  
      - fatloss
    plugin: nil
    build-snaps: 
      - gnome-42-2204
      - core22
      - gtk-common-themes
    override-prime: |
      set -eux
      for snap in "gnome-42-2204" "core22" "gtk-common-themes"; do
      cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$CRAFT_PRIME/{}" \;
      done  
      
