name: celluloid
base: core22
adopt-info: celluloid
grade: stable
confinement: strict
compression: lzo
license: GPL-3.0-or-later
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

slots:
  celluloid:
    interface: dbus
    bus: session
    name: io.github.celluloid_player.Celluloid
  mpris:
    name: Celluloid

apps:
  celluloid:
    command: usr/bin/celluloid
    extensions: [gnome]
    common-id: io.github.celluloid_player.Celluloid
    desktop: usr/share/applications/io.github.celluloid_player.Celluloid.desktop
    plugs:
      - home
      - audio-playback
      - bluez
      - network
      - network-bind
      - network-status
      - removable-media
      - unity7
      - screen-inhibit-control
    slots:
      - mpris

parts:
  ffmpeg:
    plugin: autotools
    source: https://ffmpeg.org/releases/ffmpeg-7.0.tar.gz
    autotools-configure-parameters:
      - --prefix=/usr
      - --libdir=/usr/lib/$CRAFT_ARCH_TRIPLET
      - --disable-debug
      - --disable-doc
      - --disable-static
      - --enable-gpl
      - --enable-shared
      - --disable-ffplay
      - --disable-devices
      - --enable-gnutls
      - --enable-libmp3lame
      - --enable-libvorbis
      - --enable-libdav1d
      - --enable-libopus
      - --enable-libx264
      - --enable-libx265
      - --enable-libvpx
    build-packages:
      - nasm
      - libmp3lame-dev
      - libvorbis-dev
      - libopus-dev
      - libx264-dev
      - libx265-dev
      - libnuma-dev
      - libvpx-dev
      - libdav1d-dev
    stage-packages:
      - libmp3lame0
    prime:
      - -usr/share/doc
      - -usr/share/man
      - -usr/share/ffmpeg/examples
      - -usr/include
      - -usr/lib/*/pkgconfig

  mpv:
    source: https://github.com/mpv-player/mpv.git
    source-tag: v0.35.1
    after: [ffmpeg]
    plugin: meson
    meson-parameters:
      - -Dprefix=/usr
      - -Dbuildtype=release
      - -Dlibmpv=true
      - -Dx11=enabled
      - -Dwayland=enabled
      - -Dshaderc=disabled
      - -Dpipewire=disabled
      - -Dalsa=disabled
      - -Djack=disabled
      - -Dsndio=disabled
      - -Dsysconfdir=/snap/mpv/current/usr/share
      - -Ddrm=enabled
    build-packages:
      - curl
      - libx264-dev
      - libass-dev
      - libvorbis-dev
      - libjpeg-turbo8-dev
      - libxss-dev
      - libxpresent-dev
      - liblua5.2-dev
    prime:
      - -usr/share/man
      - -usr/share/help
      - -usr/include
      - -usr/lib/*/pkgconfig

  celluloid:
    source: https://github.com/celluloid-player/celluloid.git
    source-tag: 'v0.26'
    source-depth: 1
    after: [mpv]
    plugin: meson
    parse-info: [usr/share/metainfo/io.github.celluloid_player.Celluloid.appdata.xml]
    meson-parameters:
      - -Dprefix=/usr
    build-packages:
      - libass-dev
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0 | cut -c 2-)
      sed -e 's|Icon=io.github.celluloid_player.Celluloid|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/io.github.celluloid_player.Celluloid.svg|' -i data/io.github.celluloid_player.Celluloid.desktop.in
    prime:
      - -usr/share/man
      - -usr/include
      - -usr/lib/*/pkgconfig

  deps:
    plugin: nil
    after: [celluloid]
    stage-packages:
      - libxpresent1
      - libxss1
      - libass9
      - liblua5.2-0
      - libdav1d5
      - libnuma1
      - libx264-163
      - libx265-199
      - libass9
      - libvdpau1
      - libvpx7
    prime:
      - usr/lib/*/libass*
      - usr/lib/*/libXss*
      - usr/lib/*/libXpresent*
      - usr/lib/*/liblua5.2.so*
      - usr/lib/*/libdav1d.so*
      - usr/lib/*/libnuma*
      - usr/lib/*/libx264*
      - usr/lib/*/libx265*
      - usr/lib/*/libass*
      - usr/lib/*/libvdpau*
      - usr/lib/*/libvpx*
      - -usr/lib/arm-linux-gnueabihf/libnuma.so*
