name: celluloid
base: core22
adopt-info: celluloid
grade: stable
confinement: strict
compression: lzo
license: GPL-3.0-or-later
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

slots:
  celluloid:
    interface: dbus
    bus: session
    name: io.github.celluloid_player.Celluloid
  mpris:
    name: Celluloid

apps:
  celluloid:
    command: usr/bin/celluloid
    extensions: [gnome]
    common-id: io.github.celluloid_player.Celluloid
    desktop: usr/share/applications/io.github.celluloid_player.Celluloid.desktop
    plugs:
      - home
      - audio-playback
      - bluez
      - network
      - network-bind
      - network-status
      - removable-media
      - unity7
      - optical-drive
      - screen-inhibit-control
    slots:
      - mpris

parts:
  ffmpeg:
    plugin: autotools
    source: https://ffmpeg.org/releases/ffmpeg-6.1.1.tar.xz
    autotools-configure-parameters:
      - --prefix=/usr
      - --libdir=/usr/lib/$CRAFT_ARCH_TRIPLET
      - --disable-debug
      - --disable-doc
      - --disable-static
      - --enable-gpl
      - --enable-shared
      - --disable-ffplay
      - --disable-devices
      - --enable-gnutls
      - --enable-libmp3lame
      - --enable-libvorbis
    build-packages:
      - nasm
      - libmp3lame-dev
      - libvorbis-dev
    stage-packages:
      - libmp3lame0
    prime:
      - -usr/share/doc
      - -usr/share/man
      - -usr/share/ffmpeg/examples
      - -usr/include
      - -usr/lib/*/pkgconfig

  mpv:
    source: https://github.com/mpv-player/mpv.git
    source-tag: v0.35.1
    after: [ffmpeg]
    plugin: meson
    meson-parameters:
      - -Dprefix=/usr
      - -Dbuildtype=release
      - -Dlibmpv=true
      - -Dx11=enabled
      - -Dwayland=enabled
    build-packages:
      - curl
      - libx264-dev
      - libass-dev
      - libvorbis-dev
      - libjpeg-turbo8-dev
      - libxss-dev
      - libxpresent-dev
      - liblua5.2-dev
    prime:
      - -usr/share
      - -usr/include
      - -usr/lib/*/pkgconfig

  celluloid:
    source: https://github.com/celluloid-player/celluloid.git
    source-tag: v0.26
    after: [mpv]
    plugin: meson
    parse-info: [usr/share/metainfo/io.github.celluloid_player.Celluloid.appdata.xml]
    meson-parameters:
      - -Dprefix=/usr
    build-packages:
      - libass-dev
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0 | cut -c 2-)
      sed -e 's|Icon=io.github.celluloid_player.Celluloid|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/io.github.celluloid_player.Celluloid.svg|' -i data/io.github.celluloid_player.Celluloid.desktop.in
    prime:
      - -usr/share/man
      - -usr/include
      - -usr/lib/*/pkgconfig

  deps:
    plugin: nil
    after: [celluloid]
    stage-packages:
      - libxpresent1
      - libxss1
      - libass9
      - liblua5.2-0
    prime:
      - usr/lib/*/libass*
      - usr/lib/*/libXss*
      - usr/lib/*/libXpresent*
      - usr/lib/*/liblua*

  cleanup:
    after:
      - deps
    plugin: nil
    build-snaps:
      - gnome-42-2204
      - core22
      - gtk-common-themes
    override-prime: |
      set -eux
      for snap in "gnome-42-2204" "core22" "gtk-common-themes"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$CRAFT_PRIME/{}" \;
      done
