name: celluloid
base: core22
adopt-info: celluloid  
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
  - build-on: arm64
  
slots:
  celluloid:
    interface: dbus
    bus: session
    name: io.github.celluloid_player.Celluloid
  mpris:
    name: Celluloid
    
apps:
  celluloid:
    command: usr/bin/celluloid
    extensions: [gnome]
    common-id: io.github.celluloid_player.Celluloid 
    desktop: usr/share/applications/io.github.celluloid_player.Celluloid.desktop
    plugs:
      - home
      - audio-playback
      - bluez
      - network
      - network-bind
      - network-status
      - removable-media
      - unity7
      - optical-drive
      - screen-inhibit-control
    slots:
      - mpris
    
parts: 
  ffmpeg:
    plugin: autotools
    source: https://ffmpeg.org/releases/ffmpeg-6.0.tar.xz
    source-checksum: sha256/57be87c22d9b49c112b6d24bc67d42508660e6b718b3db89c44e47e289137082
    autotools-configure-parameters:
      - --prefix=/usr
      - --libdir=/usr/lib/$CRAFT_ARCH_TRIPLET
      - --disable-debug
      - --disable-doc
      - --disable-static
      - --enable-gpl
      - --enable-shared
      - --disable-ffplay
      - --disable-devices
      - --enable-gnutls
      - --enable-libmp3lame
      - --enable-libvorbis
    build-packages:
      - nasm
      - libgnutls28-dev
      - libmp3lame-dev
      - libvorbis-dev
    stage-packages:
      - libmp3lame0
    stage:
      - -usr/share/ffmpeg/examples
    prime:  
      - -usr/include
      - -usr/lib/*/pkgconfig
     
  libass:
    source: https://github.com/libass/libass/releases/download/0.17.1/libass-0.17.1.tar.xz
    source-checksum: sha256/f0da0bbfba476c16ae3e1cfd862256d30915911f7abaa1b16ce62ee653192784
    after: [ffmpeg]
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr 
      - --disable-static 
    build-packages:
      - libfontconfig-dev
      - libfreetype-dev
    stage:
      - usr  
    prime:
      - -usr/include  
    
  mpv:
    source: https://github.com/mpv-player/mpv.git
    source-tag: v0.35.1 
    after: [libass]
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
      - -Dlibmpv=true
    build-packages:
      - curl
      - libx264-dev
      - libvorbis-dev
      - libjpeg-turbo8-dev
    stage:
      - usr  
    prime:
      - -usr/include
  
  celluloid:
    source: https://github.com/celluloid-player/celluloid.git
    source-tag: v0.25
    after: [mpv]
    plugin: meson
    parse-info: [usr/share/metainfo/io.github.celluloid_player.Celluloid.appdata.xml]
    meson-parameters:
      - --prefix=/snap/celluloid/current/usr
      - --buildtype=release
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0 | cut -c 2-)
      sed -e 's|Icon=io.github.celluloid_player.Celluloid|Icon=${SNAP}usr/share/icons/hicolor/scalable/apps/github.celluloid_player.Celluloid.svg|' -i data/io.github.celluloid_player.Celluloid.desktop.in
      patch -p1 < $CRAFT_PROJECT_DIR/local/patches/upstream.patch
    organize:
      snap/celluloid/current/usr: usr  

  cleanup:
    after:  
      - celluloid
    plugin: nil
    build-snaps: 
      - gnome-42-2204
      - core22
      - gtk-common-themes
    override-prime: |
      set -eux
      for snap in "gnome-42-2204" "core22" "gtk-common-themes"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$CRAFT_PRIME/{}" \;
      done  
      
